### ISSUE TITLE
A doubt about topicUpdating function in MedRTM

### ISSUE THREAD

**Issue by youyou606** [ywwbill/RTM_Hinge_Loss#1]
https://github.com/ywwbill/RTM_Hinge_Loss/blob/5a9661246a6a9b7b803b697d27f3b206fb458f28/src/lda/rtm/MedRTM.java#L188

Should the `MathUtil.sqr` be deleted according to the calculation formula of `weight` variables?

**Comment by ywwbill** [comment]
Sorry about it. I forgot to update this repo. Just fixed it.

Feel free to reopen if there is any further problem.
